:concurrency: 3
:timeout: 60
:verbose: true
:queues:  # Queue priority: https://github.com/mperham/sidekiq/wiki/Advanced-Options
  - default
  - mailers
:schedule:
  send_mail_job:
    cron: '0 57 11 * * *'   # Runs once per minute
    class: SendMailJob
